cookie:
  expiry_days: 30
  key: tricc_webapp_2023
  name: tricc_webapp
credentials:
  usernames:
    martin_norris:
      email: martin.norris@swisstph.ch
      name: Martin Norris
      password: $2b$12$aGY.eyJSiSL1N4i.T47wY.YmVIGxJ7Tc36Y.E0GRn64LjqYgBBqAC
    msf:
      email: msf_user@tricc.ch
      name: MSF Demo User
      password: $2b$12$ULnFsl6.bwjN.Fa88m.cp.0BbnkNQUscRX6.B3ZN8soT723X4SEQ2
    patrick_meier:
      email: patrick.meier@swisstph.ch
      name: Patrick Meier
      password: $2b$12$6mBFEt0AtbxGnZclupczRe8/PVSy9WiFU5F7ZiWPRJ6bNrgvmfHSy
    rafael_kluender:
      email: rafael.kluender@swisstph.ch
      name: Rafael Kluender
      password: $2b$12$0Lj9nSLDkQ032VfDhAgGkOhwkrAGxKD2fLXL6rxu2YOa7LER2l4JO
    swisstph:
      email: info@swisstph.ch
      name: SwissTPH Demo User
      password: $2b$12$r25Rxhex1UlSdSGw2LAd7eqjeKOyFXaVKZyJ1Zrc6HpVlJH7tdt7q
preauthorized:
  emails:
    - Job.Isabai@nairobi.msf.org
